name: marketika_website
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutterflow_ui_pro:
    path: D:\UserFiles\FlutterPackages\flutterflow-ui-pro
  aligned_tooltip: ^0.0.1
  aligned_dialog: ^0.0.7
  badges: ^3.1.2
  adaptive_theme: ^3.5.0
  carousel_slider: ^4.2.1
  icons_launcher: ^2.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

icons_launcher:
  image_path: "assets/images/icon-512.png"
  platforms:
    web:
      enable: true
      image_path: "assets/images/icon-512.png"
      favicon_path: "assets/images/icon-512.png"
