name: marketika_website
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutterflow_ui_pro:
    path: D:\User Files\Projects\FlutterPackages\flutterflow_ui_pro
  aligned_tooltip: ^0.0.1
  aligned_dialog: ^0.0.7
  badges: ^3.1.2
  adaptive_theme: ^3.6.0
  carousel_slider: ^4.2.1
  icons_launcher: ^2.1.7
  youtube_player_flutter: ^9.0.1
  youtube_player_iframe: ^5.1.2
  supabase_flutter: ^2.5.6
  flutter_dotenv: ^5.1.0
  url_launcher: ^6.3.0
  intl: ^0.19.0
  fluttertoast: ^8.2.6
  flutter_quill: ^9.4.5
  meta_seo: ^3.0.9
  flutter_inappwebview: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env

icons_launcher:
  image_path: "assets/images/icon-512.png"
  platforms:
    web:
      enable: true
      image_path: "assets/images/icon-512.png"
      favicon_path: "assets/images/icon-512.png"
